### ISSUE TITLE
Add Automatic-Module-Name to manifest

### ISSUE THREAD

**Issue by skuzzle** [cglib/cglib#146] opened 2019-01-26 09:36 UTC
I understand that a full migration to java9 would not be that easy but how about at least adding an `Automatic-Module-Name` entry to the jar's manifest file? That would make it easier for dependent projects to migrate to java 9.

Its as simple as this:
```
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <configuration>
                        <archive>
                            <manifestEntries>
                                <Automatic-Module-Name>net.sf.cglib</Automatic-Module-Name>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>
```

**Comment by raphw** [comment] 2019-01-28 08:44
I agree that this should be added. Do you mind creating a pull request=

**Comment by skuzzle** [comment] 2019-01-28 10:08
I don't mind. I'm not quite sure about all the sub modules though. I believe the module name should be sufficient for the main artficat `cglib`?
And, are you ok with the module name `net.sf.cglib` that I chose? I believe there are not many other reasonable names that we could go for.

**Comment by raphw** [comment] 2019-01-28 12:19
I think the root package notation should work. I suggest to only add it to cglib-nodep.

**Comment by skuzzle** [comment] 2019-01-28 13:08
Really? Isn't `cglib` the main artifact that people depend on? According to the GitHub dependency checks there are ~21k repositories depnending on `cglib-nodep` but ~44k depending on `cglib`.
If I understand correctly one would either use one or the other? If so, maybe we could give both the same automatic module name?

**Comment by raphw** [comment] 2019-01-28 15:48
Fair point, but the problem is that you can only really use one of the two as there would be package conflicts either. I would therefore think that people who want to modularize their app should shift over to the nodep version, otherwise, module consistency would break anyways if both artifacts were released as automatic modules.

**Closed** 2019-01-29 06:19 UTC
