### ISSUE TITLE
Release CGLIB 3.1.x?

### ISSUE THREAD

**Issue by guw** [cglib/cglib#20] opened 2014-09-19 07:31 UTC
I'm interested in getting a new release of CGLIB up on Maven Central which can be consumed by downstream projects. I need pull request #15 for Mockito but they only consume official releases.

Can I pretty please get a release?

**Comment by shendrix** [comment] 2015-03-13 20:21
This issue is a problem for us too: IllegalArgumentException when using Java8.

**Comment by kbaughman** [comment] 2015-03-13 20:36
Upgrade to EasyMock 3.3.1. It has been released with support for Java 8.

**Comment by shendrix** [comment] 2015-03-13 20:53
We use Spock, which in turn uses Cglib

**Comment by raphw** [comment] 2015-03-14 15:43
The error is caused by using the old `Opcodes.ASM4` constants which prohibiti the parsing of Java 8 files for determining potential bridge methods. If cglib is upgraded to use ASM 5 with the `Opcodes.ASM5` constant, the exception should not longer be thrown.

We have already upgraded to ASM 5 but we miss some work to properly test the Java 8 compatibility, therefore, no release was yet made.

**Comment by mjedynak** [comment] 2015-04-01 18:28
I used current version from master (commit 6238d92d7) on a proprietary project that relies heavily on cglib and has a lot of regression tests - did not see any issues. Is there any chance to release it to maven central soon?

**Comment by DriesSchulten** [comment] 2015-04-16 09:09
We also use Spock and are very interested in a new release that works with Java 8.

**Comment by javaspiver** [comment] 2015-04-17 13:44
Same here - any chance for a new release in the nearest future?

**Comment by HiJon89** [comment] 2015-04-27 13:19
I'm not sure of the status of #18, but for what it's worth we've been running CGLIB master across our 600+ Java projects for over a month without issue

**Comment by leonard84** [comment] 2015-05-30 20:27
Any timeline for 3.2.0?

**Comment by iNikem** [comment] 2015-06-03 12:34
So after a year of releasing java 8 and after java 7 is officially dead there is still no release which supports java 8? I understand that this is Open Source and community driven, but the question here is not about contribution. Code is already here. It should be only released. And this cannot be done by community. This have to do you, official maintainers of the project.

Can you please release the code that you already have and that the community eagerly looks for?

**Comment by raphw** [comment] 2015-06-03 13:00
For those looking for an urgent alternative: https://github.com/raphw/byte-buddy || http://bytebuddy.net

**Comment by czerwinb** [comment] 2015-08-21 06:55
Hi all, a quick note regarding CGLIB 3.1 not supporting Java 8. We have used pure CGLIB 3.1 release with overriden ASM 5.0.3 and that works. So far no issues reported. Anyone tried something similar?

**Comment by jhaber** [comment] 2015-08-21 12:45
We ran that setup briefly and I don't remember having any serious problems (but I think it was a ticking time-bomb), but once we enabled [parameter name reflection](http://www.software-architect.net/articles/new-features-in-java-8/parameter-name-reflection.html) by compiling with the new `-parameters` javac flag, everything broke immediately. 

However, #34 seems to have fixed the remaining Java 8 compatibility issues, we've been building and running the master branch including that PR for 5 months now without issue.

**Comment by bwzhang2011** [comment] 2015-09-18 02:00
@jhaber, any update with such issue ? maybe cglib3.2 should be released compared to release of javasist recently.

**Comment by jhaber** [comment] 2015-09-18 02:14
Nothing new to report, we've been running the master branch of CGLIB for 6 months now across our 1,000+ Java projects without issue. Version 3.1 was horribly broken for us once we started compiling with the new `-parameters` flag but once #34 was merged it has been smooth sailing

**Comment by sameb** [comment] 2015-10-28 15:52
released 3.2.0.  might take a while for maven/central to get everything updated.

**Closed by sameb** 2015-10-28 15:52 UTC
