### ISSUE TITLE
3.2 release request

### ISSUE THREAD

**Issue by jhalterman** [cglib/cglib#43] opened 2015-09-18 17:47 UTC
@sameb Can we get a 3.2 release? 

I recently [became aware](https://github.com/jhalterman/modelmapper/issues/162) that 3.1, which uses ASM 4x has a problem generating classes via `Enhancer` when using the `-parameters` option in JDK 8 built projects. The latest in master, which uses ASM 5x, seems to work fine - we just need a new release!

Regarding impact, right now this effects basically any library using 3.1, including Guice, Spring, ModelMapper (my library), etc.

**Comment by jhoeller** [comment] 2015-10-06 21:04
FWIW, we actually bind our own jarjar'ed CGLIB 3.1 to ASM 5 in Spring Framework 4.x - in order for it to work fine with the 1.8 bytecode level.

That said, +1 from my side for releasing CGLIB 3.2! We'd immediately pick it up in Spring Framework 4.3 at least, possibly even in the 4.2.x line.

**Comment by jhalterman** [comment] 2015-10-06 21:06
@jhoeller I was thinking about something like that. Just to be clear - are you compiling the latest cglib from source and bundling with Spring, or just repackaging the existing 3.1 classfiles with ASM 5? (I assumed there might be some ASM API changes which would prevent a repackaging from working).

**Comment by jhoeller** [comment] 2015-10-06 21:15
@jhalterman We're currently repacking CGLIB 3.1 proper, binding it to our own repackaged version of ASM 5. This works fine for our purposes but I'm sure it has some limitations in general, since CGLIB explicitly specifies its visitor classes to be at ASM 4 level. The proper solution is certainly the way it's done in CGLIB master, with explicit ASM 5 support, and this really should get released as CGLIB 3.2!

**Comment by jhalterman** [comment] 2015-10-06 22:42
@jhoeller Thanks for the info. At least I have a workaround if needed.

**Comment by jhaber** [comment] 2015-10-12 20:19
Duplicate of #20? (or we could close both issues by releasing 3.2 :wink: )

**Comment by SveTob** [comment] 2015-10-14 09:22
+1 on this. It is way overdue to do either a minor or major release. As far as I can tell, _master_ is better than 3.1 in every way, so there is no reason not to do a 3.1.1 or 3.2 release!

**Comment by sameb** [comment] 2015-10-28 15:51
released.  might take a while for maven/central to figure everything out.

**Closed by sameb** 2015-10-28 15:51 UTC

**Comment by jhalterman** [comment] 2015-10-28 19:42
Thanks @sameb

**Comment by jhoeller** [comment] 2015-10-29 12:02
Many thanks for the timely release, @sameb! I've upgraded Spring Framework master to CGLIB 3.2 and all lights are green, so we'll include it in our 4.2.3 release next week right away...

**Comment by sameb** [comment] 2015-10-29 12:59
Glad the timing worked out for you.

**Comment by SveTob** [comment] 2015-10-30 23:07
Thanks for the release!
